export const SET_EVENT_SAVE_APPLICATION_SUCCESS =
  'SET_EVENT_SAVE_APPLICATION_SUCCESS'
export const SET_INDUSTRY_TYPE_CODE_NOT_VALID_ERROR =
  'SET_INDUSTRY_TYPE_CODE_NOT_VALID_ERROR'
export const SET_EVENT_PAYMENT_UNSUCCESS = 'SET_EVENT_PAYMENT_UNSUCCESS'
export const COMMIT_APPROVED_PAYMENT_INFO = 'COMMIT_APPROVED_PAYMENT_INFO'
export const COMMIT_UNKNOWN_PAYMENT_INFO = 'COMMIT_UNKNOWN_PAYMENT_INFO'
export const COMMIT_COMPLETE_APPLICATION_INFO =
  'COMMIT_COMPLETE_APPLICATION_INFO'
