export const SET_CRM_CONTACT = 'SET_CRM_CONTACT'
export const UPDATE_CRM_CONTACT = 'UPDATE_CRM_CONTACT'
export const RESET_CRM_CONTACT = 'RESET_CRM_CONTACT'
export const SET_CRM_CONTACT_FAIL = 'SET_CRM_CONTACT_FAIL'
