export { default as authModule } from './auth'
export { default as userProfileModule } from './userprofile'
export { default as applicationModule } from './application'
export { default as calendarModule } from './calendar'
export { default as contactModule } from './contact'
export { default as skillsGroupContactModule } from './skills-group-portal/contact'
export { default as skillsGroupApplicationModule } from './skills-group-portal/application'
export { default as azureADB2CModule } from './b2c-auth'
